before:
  hooks:
  - go mod download
builds:
- id: Build
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  env:
  - CGO_ENABLED=0
snapshot:
  name_template: "snapshot-{{ .Commit }}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
