on:
- push:
    branches:
    - master
- pull_request
name: ci
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v1
      with:
        go-version: '1.13'
    - run: go build
    - run: go vet
